[[local|localrc]]
############################################################
# Customize the following HOST_IP based on your installation
############################################################
HOST_IP=0.0.0.0

ADMIN_PASSWORD=devstack
MYSQL_PASSWORD=devstack
RABBIT_PASSWORD=devstack
SERVICE_PASSWORD=$ADMIN_PASSWORD
SERVICE_TOKEN=devstack

############################################################
# Customize the following section based on your installation
############################################################

# Pip
PIP_USE_MIRRORS=False
USE_GET_PIP=1

#OFFLINE=False
#RECLONE=True

# Logging
DEST=/opt/stack/
LOGFILE=$DEST/logs/stack.sh.log
VERBOSE=True
ENABLE_DEBUG_LOG_LEVEL=True
ENABLE_VERBOSE_LOG_LEVEL=True

# Neutron ML2 with OpenVSwitch
Q_PLUGIN=ml2
Q_AGENT=ovn

# Disable security groups
LIBVIRT_FIREWALL_DRIVER=nova.virt.firewall.NoopFirewallDriver

# Enable heat, networking-sfc and barbican
enable_plugin neutron https://opendev.org/openstack/neutron stable/2024.2
enable_plugin heat https://opendev.org/openstack/heat stable/2024.2
enable_plugin heat-dashboard https://opendev.org/openstack/heat-dashboard stable/2024.2
enable_plugin networking-sfc https://opendev.org/openstack/networking-sfc stable/2024.2
enable_plugin barbican https://opendev.org/openstack/barbican stable/2024.2

# Aodh
enable_plugin aodh https://opendev.org/openstack/aodh stable/2024.2
enable_plugin ceilometer https://opendev.org/openstack/ceilometer stable/2024.2

# Gnocchi settings
# Gnocchi is optional but can be enbaled by uncommenting CEILOMETER_BACKEND
CEILOMETER_BACKEND=gnocchi

# if gnocchi is not in LIBS_FROM_GIT it will install from pypi.
# Currently this is broken with the latest gnocchi release 4.4.2
# so we need to install from git until
# https://github.com/gnocchixyz/gnocchi/issues/1290 is resolved
LIBS_FROM_GIT+=gnocchi

GIT_BASE=https://opendev.org
# Octavia
enable_plugin octavia https://opendev.org/openstack/octavia stable/2024.2
enable_plugin octavia-dashboard $GIT_BASE/openstack/octavia-dashboard stable/2024.2
enable_plugin ovn-octavia-provider $GIT_BASE/openstack/ovn-octavia-provider stable/2024.2
enable_service octavia o-api o-cw o-hm o-hk o-da

# Tacker
enable_plugin tacker https://opendev.org/openstack/tacker stable/2024.2

# Zaqar
# enable_plugin zaqar-ui https://github.com/openstack/zaqar-ui stable/2024.2
# enable_plugin zaqar https://opendev.org/openstack/zaqar stable/2024.2

# Mistral
# enable_plugin mistral https://github.com/openstack/mistral stable/2024.2

enable_service n-novnc
enable_service n-cauth

disable_service tempest

[[post-config|/etc/neutron/dhcp_agent.ini]]
[DEFAULT]
enable_isolated_metadata = True

# NOTE: workaround for Cinder image volume cache problem.
# https://bugs.launchpad.net/cinder/+bug/1953704
[[post-config|/etc/cinder/cinder.conf]]
[lvmdriver-1]
image_volume_cache_enabled = False
