heat_template_version: wallaby
description: >
  Base HOT for Sample VNF

parameters:
  nfv:
    type: json
  VDU1-scaling:
    type: json
  VDU1-scale-level:
    type: json

resources:
  VDU1:
    type: OS::Heat::Stack
    depends_on: VDU1_fake_asg
    properties:
      template: { get_file: VDU1.yaml }
      parameters:
        ram:
          {
            get_param:
              [
                VDU1-scaling,
                scale-levels,
                { get_attr: [VDU1_fake_asg, current_size] },
                ram,
              ],
          }
        vcpu:
          {
            get_param:
              [
                VDU1-scaling,
                scale-levels,
                { get_attr: [VDU1_fake_asg, current_size] },
                vcpu,
              ],
          }
        image: { get_param: [nfv, VDU, VDU1, vcImageId] }
        net1: { get_param: [nfv, CP, VDU1_CP1, network] }
        subnet1: { get_param: [nfv, CP, VDU1_CP1, fixed_ips, 0, subnet] }
        security_group: { get_param: [nfv, CP, VDU1_CP1, security_group] }
        key_name: { get_param: [nfv, VDU, VDU1, key_name] }
        root_stack_id: { get_param: "OS::stack_id" }
  cpu_alarm_high:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale up if CPU > threshold
      metric: cpu ## important    cpu, not cpu_util
      aggregation_method: rate:mean
      granularity: 300
      evaluation_periods: 2
      threshold:
        {
          get_param:
            [
              VDU1-scaling,
              scale-levels,
              { get_param: VDU1-scale-level },
              cpu_threshold_hi,
            ],
        }
      resource_type: instance
      comparison_operator: gt
      alarm_actions:
        if:
          - { get_param: [VDU1-scaling, enable_autoscale] }
          - - str_replace:
                template: trust+url
                params:
                  url: { get_attr: [VDU1_scale_up, signal_url] }
      query:
        str_replace:
          template: '{"=": {"id": "VDU1_id"}}'
          params:
            VDU1_id: { get_attr: [VDU1, outputs, instance_id] }

  cpu_alarm_low:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale down if CPU < threshold
      metric: cpu
      aggregation_method: rate:mean
      granularity: 300
      evaluation_periods: 2
      threshold:
        {
          get_param:
            [
              VDU1-scaling,
              scale-levels,
              { get_param: VDU1-scale-level },
              cpu_threshold_lo,
            ],
        }
      resource_type: instance
      comparison_operator: lt
      alarm_actions:
        if:
          - { get_param: [VDU1-scaling, enable_autoscale] }
          - - str_replace:
                template: trust+url
                params:
                  url: { get_attr: [VDU1_scale_down, signal_url] }
      query:
        str_replace:
          template: '{"=": {"id": "VDU1_id"}}'
          params:
            VDU1_id: { get_attr: [VDU1, outputs, instance_id] }

  VDU1_fake_asg:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 0
      max_size: 2
      desired_capacity: { get_param: VDU1-scale-level }
      cooldown: 600
      resource:
        type: OS::Heat::RandomString
        properties:
          length: 32

  VDU1_scale_up:
    type: OS::Heat::ScalingPolicy
    properties:
      scaling_adjustment: 1
      cooldown: 900
      auto_scaling_group_id:
        get_resource: VDU1_fake_asg
      adjustment_type: change_in_capacity

  VDU1_scale_down:
    type: OS::Heat::ScalingPolicy
    properties:
      scaling_adjustment: -1
      cooldown: 600
      auto_scaling_group_id:
        get_resource: VDU1_fake_asg
      adjustment_type: change_in_capacity

outputs:
  website_url:
    value:
      str_replace:
        template: http://host/
        params:
          host: { get_attr: [VDU1, outputs, vdu1_floating_ip] }
    description: >
      This URL is the "external" URL that can be used to access the
      Wordpress site.

  instance_id:
    description: "ID of VDU1"
    value: { get_attr: [VDU1, outputs, instance_id] }
