heat_template_version: rocky
description: 'Sample VDU HOT'

parameters:
  flavor:
    type: string
  image:
    type: string
  zone:
    type: string
  net1:
    type: string
  net2:
    type: string
  # subnet1:
  #   type: string
  subnet2:
    type: string
  ip_address:
    type: string
  security_group:
    type: string
    default: default

resources:
  VDU1:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      name: VDU1
      image: { get_param: image }
      networks:
      - port:
          get_resource: VDU1_CP0
      - port:
          get_resource: VDU1_CP1
      availability_zone: { get_param: zone }

  # internal VL
  VDU1_CP0:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net1 }

  # extVL with numDynamicAddresses and subnet
  VDU1_CP1:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net2 }
      fixed_ips:
      - subnet: { get_param: subnet2 }
      # - ip_address: { get_param: ip_address }

