heat_template_version: wallaby
description: "imple Base HOT for Sample VNF"

parameters:
  nfv:
    type: json
  security_group:
    type: string
    default: default
  api_params:
    type: json
  key_name:
    type: string
    
  enable_auto_scaling:
    type: boolean
    default: true
  enable_auto_healing:
    type: boolean
    default: true

  cpu_threshold_high:
    type: number
  cpu_threshold_low:
    type: number

resources:
  internalVL1:
    type: OS::Neutron::Net

  internalVL1_subnet:
    type: OS::Neutron::Subnet
    depends_on: [internalVL1]
    properties:
      ip_version: 4
      network:
        get_resource: internalVL1
      cidr: 192.168.0.0/24

  VDU1_scale_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      max_size: 3
      desired_capacity: { get_param: [nfv, VDU, VDU1, desired_capacity] }
      resource:
        type: VDU1.yaml
        properties:
          flavor: { get_param: [nfv, VDU, VDU1, flavor] }
          image: { get_param: [nfv, VDU, VDU1, image] }
          # zone: { get_param: [nfv, VDU, VDU1, zone] }
          net1: { get_resource: internalVL1 }
          net2: { get_param: [nfv, CP, VDU1_CP1, network] }
          # subnet1: { get_param: [nfv, CP, VDU1_CP0, fixed_ips, 0, subnet ]}
          subnet2: { get_param: [nfv, CP, VDU1_CP1, fixed_ips, 0, subnet] }
          security_group: { get_param: security_group }
          key_name: { get_param: key_name }
          metadata: {"metering.server_group": {get_param: "OS::stack_id"},
                     "stack_id": {get_param: "OS::stack_id"},
                     "stack_name": {get_param: "OS::stack_name"}}
          root_stack_id: {get_param: "OS::stack_id"}
          enable_auto_healing: { get_param: enable_auto_healing }
  
  VDU1_scale_out:
    type: OS::Heat::ScalingPolicy
    properties:
      scaling_adjustment: 1
      auto_scaling_group_id:
        get_resource: VDU1_scale_group
      adjustment_type: change_in_capacity

  VDU1_scale_in:
    type: OS::Heat::ScalingPolicy
    properties:
      scaling_adjustment: -1
      auto_scaling_group_id:
        get_resource: VDU1_scale_group
      adjustment_type: change_in_capacity

  cpu_alarm_high:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      enabled: { get_param: enable_auto_scaling }
      description: Scale up if CPU > 80%
      metric: cpu ## important    cpu, not cpu_util
      aggregation_method: rate:mean
      granularity: 300
      evaluation_periods: 3
      threshold: 480000000000.0
      resource_type: instance
      comparison_operator: gt
      alarm_actions:
        - str_replace:
            template: trust+url
            params:
              url: {get_attr: [VDU1_scale_out, signal_url]}
      query:
        str_replace:
          template: '{"=": {"server_group": "stack_id"}}'
          params:
            stack_id: {get_param: "OS::stack_id"}

  cpu_alarm_low:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      enabled: { get_param: enable_auto_scaling }
      description: Scale down if CPU < 20%
      metric: cpu
      aggregation_method: rate:mean
      granularity: 300
      evaluation_periods: 3
      threshold: 120000000000.0
      resource_type: instance
      comparison_operator: lt
      alarm_actions:
        - str_replace:
            template: "trust+url"
            params:
              url: {get_attr: [VDU1_scale_in, signal_url]}
      query:
        str_replace:
          template: '{"=": {"server_group": "stack_id"}}'
          params:
            stack_id: {get_param: "OS::stack_id"}

outputs:
  scale_group_private_ips:
    description: "Test5"
    value: { get_attr: [VDU1_scale_group, outputs_list, vdu1_external_ip] }  
  
  VDU1_scale_out_signal_url:
    value: {get_attr: [VDU1_scale_out, signal_url]}

  VDU1_scale_in_signal_url:
    value: {get_attr: [VDU1_scale_in, signal_url]}
